---
version: '3.8'

services:
  cache:
    image: redis:7.2
    command: redis-server --appendonly yes --loglevel verbose --save 20 1 --requirepass dev
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../.:/workspace:cached
      - ~/.ssh:/root/.ssh:cached
    network_mode: service:cache
    command: sleep infinity
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: dev
    depends_on:
      - cache

volumes:
  cache:
    driver: local
